### PR TITLE
docs: Codeberg

### PR DESCRIPTION
**Pull request by NameLessGO**
## Description
Changed [Codeberg](https://codeberg.org/) from Git Hosting to GitHub alternative alongside GitLab
Changed [FSRE](https://git.fsfe.org/) from GitHub alternative to Git Hosting

## Context

Codeberg has [Codeberg Pages](https://codeberg.page/), [Weblate Translations](https://translate.codeberg.org/), [Woodpecker CI](https://docs.codeberg.org/ci/#using-codeberg's-instance-of-woodpecker-ci) and [Forgejo API](https://codeberg.org/api/swagger) which works as alternative to GitHub Pages, GitHub CI/CD + Git and Translation libre hosting and self-hosted setup via Forgejo

These features make Codeberg as GitHub alternative, alongside GitLab, not git hosting

FSRE is not a GitHub alternative because it does not provide anything other than git hosting via Gitea

## Types of changes

- [ ] Bad / Deleted sites removal
- [X] Grammar / Markdown fixes 
- [ ] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [X] I have read the [contribution guide](https://rentry.co/Contrib-Guide).
- [X] I have made sure to [search](https://raw.githubusercontent.com/fmhy/FMHYedit/main/single-page) before making any changes. 
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by NameLessGO** [comment]
Gitea is already being mentioned at the bottom, if it wasn't would put them alongside GitLab and Codeberg to receive :star:

[Gitea](https://about.gitea.com/) / [2](https://gittea.dev/), [CDM Project](https://cdm-project.com/), [Forgejo](https://forgejo.org/) or [Drift](https://drift.lol/) - Self-Hosted Git Services / Forge

**Comment by NameLessGO** [comment]
Wasn't sure on which order was being used for websites in the same line

Alphabetic order: Codeberg, GitLab

Popularity order: GitLab, Codeberg

In the end used popularity, although would prefer for Codeberg to be first because it is fully open source

**Comment by nullish-cat** [comment]
It's the same kind of sorting as the rest of the wiki, so mainly quality / popularity. I recommend placing Codeberg first.

[Sourcehut](https://sr.ht) ([installation docs](https://man.sr.ht/installation.md)) can also be added in the self-hosted git list, and possibly in Git Hosting whenever it comes out of Alpha and becomes free to make projects.

**Comment by NameLessGO** [comment]
@nullish-cat Thanks for the suggestion, sourcehut was added in GH alternatives, but since the visual and workflow is drastically different to GH + premium features, then had to put in last

Summary:
sourcehut: GitHub alternative
Gitea: Forge -> GitHub Alternative
Gittea.dev and CDM-project: Forge -> Git Hosting
Drift: Forge -> New entry: GitHub Gist Alternative

**Comment by nullish-cat** [comment]
Sourcehut is self-hostable, that's why I suggested it for Git Hosting.

**Comment by NameLessGO** [comment]
Added as Github alternative because sourcehut provides more than Git Hosting (IRC, Mailing list, ticket tracking, code review tools

**Pull request merged**
