### PR TITLE
Update VideoPiracyGuide.md for RiveKun in Anime Streaming

### PR DESCRIPTION
**Pull request by dev-AshishRanjan**
## Description
Added Two domains for RiveKun
1. https://rivekun.rivestream.live  : cached by cloudflare
2. https://rivekun.pages.dev  : cloudflare pages deployment

## Context

RiveKun is an extension of Rive for Anime Streaming built on Anilist  
It provides Ad-free streaming using gogoanime and 3 other providers 

## Types of changes

- [ ] Bad / Deleted sites removal
- [ ] Grammar / Markdown fixes 
- [x] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [x] I have read the [contribution guide](https://rentry.co/Contrib-Guide).
- [x] I have made sure to [search](https://raw.githubusercontent.com/fmhy/FMHYedit/main/single-page) before making any changes. 
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by IntNinja** [comment]
I think the certificate is down, it shows "Not Secure" there's Let'sEncrypt Free SSL @dev-AshishRanjan

**Comment by dev-AshishRanjan** [comment]
@IntNinja ,
RiveKun is using free  Let'sEncrypt Free SSL
It may take some time as it was added to the custom domain recently

**Comment by dev-AshishRanjan** [comment]
The domain rivestream.live is using Let'sEncrypt Free SSL
So it's subdomains automatically uses same SSL

If still it's showing "Not secure", then can you check for https://rivestream.live
In my system it's not showing "Not Secure"

**Comment by IntNinja** [comment]
> The domain rivestream.live is using Let'sEncrypt Free SSL So it's subdomains automatically uses same SSL
> 
> If still it's showing "Not secure", then can you check for https://rivestream.live In my system it's not showing "Not Secure"

Yeah the main domain doesn't show "Not Secure", it maybe just the subdomain that's taking time, everyday you learn a new thing 😄

**Comment by IntNinja** [comment]
Also i wanted to mention something, it's great you added contextmenu and devtools disabler, but that can be bypassed using "Enable Right Click". Not sure if i can call it vulnerability but just reporting it to you. @dev-AshishRanjan 

this message will self-destruct after you reacted with an emoji

**Pull request merged**
