### PR TITLE
Debloated Indexes section, moved Alternative Sites out of storage, and more

### PR DESCRIPTION
**Pull request by the9655a**
## Changes:

**Indexes Changes:**
- Debloated Indexes section and organized links.
- Corrected titles and tags.
- Added 2 new subsections.
- Moved:
	- "SNAKE WAREZ" under Privacy Indexes
- Removed:[^1]
	- "[Dbzer0 Megathread](https://wiki.dbzer0.com/piracy/)" - lacking (content wise) compared to the r/piracy megathread + it's not updated much.
	- rentry.org mirror of r/piracy megathread - no difference between .co and .org.
	- "[Esoterica Avenue](https://ori5000.github.io/)" - doesn't have a lot of pages, most of which aren't useful. a lot of the stuff there is common knowledge and easily searchable in similar wikis or via search engines, many pages outdated with old advice, some guides might not work anymore due to no updates + offers nothing new.
	- "[CS.RIN Mega](https://cs.rin.ru/forum/viewtopic.php?f=10&t=95461)" - not sure it provides anything new.
	- "[WebOas.is](https://weboasis.app/)" - more of a startpage than an index (already in the wiki), I don't think their lists are updated much anymore anyway or put much care into quality; archive is 2 years old.
	- "[blooem](https://blooem.pages.dev/)" - wiki is sparsely updated (theres a notice on the first page), so most pages aren't being updated anymore and have outdated info/links, nothing new either.
	- "[The Pirate List](https://thepiratelist.com/)" - lists unsafe sites.
	- "[PiracyBank](https://piracybank.org/websites)" - not sure if its useful.
	- "[No-Signup Tools](https://www.nosignup.tools/)" - blank page.
	- "[BOOKMRKS-MTHRFCKR](https://github.com/whoisdsmith/BOOKMRKS-MTHRFCKR-II)" - doesn't seem very popular, likely because the links are poorly organized, but also because I feel its links are more quantity over quality.
	- "[The More You Know](https://marckoxx.github.io/)" - no updates in 2 years, not very popular either.
	- "[Cool Websites](https://rentry.co/cool_websites)" - nothing new from what I can see.
	- "[itch.io Tools](https://itch.io/tools/free)" - not sure it's useful.
	- "[ODP](http://odp.org/)" - not sure it's updated anymore.

**Alternative Sites Changes:**
- Moved:
	- "Slant" under - more of a product rankings site but happens to have alternative lists too.
- Removed:
	- "[Ethical](https://ethical.net/)" - a lot of the stuff here u can find elsewhere, some lists aren't that useful either.
	- "[switching.software](https://switching.software/)" - no updates in 3 years.
	- "[gofoss.net](https://gitlab.com/curlycrixus/gofoss)" - no active development.
	- "[Top Best Alternatives](https://www.topbestalternatives.com/)", "[Xranks](https://xranks.com/)" - not the best recommendations or search.
	- "[Free Competitors](https://notabug.org/jyamihud/FreeCompetitors)" - not very popular, only 5 stars, rough interface, doesn't seem very useful.
	- "[Similar Sites](https://www.similarsites.com/)" - not very good similarity scores.
	- "[SimilarWeb](https://www.similarweb.com/)" - paid.
	- "[odir.us](https://odir.us/)" - no search + not sure it's useful.
	- "[TopSimilarSites](https://www.topsimilarsites.com/)" - hardly any sites + the ones they have are super common and can be found elsewhere.

**Other Changes:**
- Organized Search Tools entries to be more site-readable.
- Starred AccuWeather - just a good weather app, that's all. has all the features you could want/think of.
- Moved:
	- Mobile map apps under Maps and replaced with redirect link for Navigation / Transport maps.
	- YouTube ReVanced for Android 6.0-7.1 in-line.
	- YT Guide to the front.
	- "Travel Safe Abroad" - under Flights.
	- "Git Install" with the rest of the greasy fork tools.
- Added:
	- New Weather Apps section.
	- New ReVanced Tools section.
	- "Note" for Eaglercraft.
- Removed:
	- "[Flux](https://play.google.com/store/apps/details?id=de.bendix.flux)" - no updates in 2 years.
	- "[AT-YT](https://github.com/Zenlua/AT-YT)" - only builds apks for revanced extended, which was discontinued.

[^1]: If I've removed any entries created by FMHY members, please note that my goal is to evaluate content objectively. Of course, I have no personal issues with the creators of these wikis. However, if an entry is outdated, lacks substance, or doesn't offer anything unique, then I think we should prioritize its quality over personal connections, instead of keeping entries solely because of who made them.

### CODE REVIEW

**Comment by nbats** [comment]
I'm getting this 

image

**Comment by the9655a** [comment]
Click on the dropdown arrow, are there any other options there?

**Comment by the9655a** [comment]
Hm. Do u have any pending changes that you've not saved yet? Like, from editing the md files on github.

**Comment by nbats** [comment]
alright I think I just got it

**Comment by the9655a** [comment]
Oh sick, what did you do?

**Comment by nbats** [comment]
Tasky said just to squash them

**Pull request merged**
