### PR TITLE
Update VideoPiracyGuide.md

### PR DESCRIPTION
**Pull request by KickassAnimeOfficial**
Hello,

I've made a small update to our Video Piracy Guide. Now, it includes a link to KickassAnime (https://kickassanime.co.in/), a site for free anime streaming. This should be a great resource for our readers.

Best,
KickAssAnime

### CODE REVIEW

**Comment by KickassAnimeOfficial** [comment]
Sorry for that,,

**Comment by KickassAnimeOfficial** [comment]
Did you review our website?

**Comment by nbats** [comment]
> Did you review our website?

Thank you but this doesn't seem to have anything to do with the real KAA. They have a discord with over 28k members which isn't linked anywhere on the site, and they dont have this version of the site linked anywhere on their discord as a backup.

**Comment by KickassAnimeOfficial** [comment]
Hi,

Thanks again for looking at kickassanime.co.in. I understand there might be concerns linking to our main domain since we're an independent platform and not directly affiliated with the main KAA community.

However, considering our site offers relevant and quality anime content, much like the other sites you've linked, would it be possible to compromise by linking to a specific episode on our site instead? This way, your audience can still benefit from the diverse content we offer.

We aim to provide value to anime fans and believe even a smaller collaboration like this could be beneficial for both our audiences. Of course, I'm open to any other suggestions you might have and respect your decision-making process in this matter.

Looking forward to your response.

Best regards,

**Pull request closed without merging**
