### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DogancanYr**
It's a shame they didn't fix the android app.

### CODE REVIEW

**Comment by nbats** [comment]
ty added some changes but I dont want to mess with the images

**Comment by DogancanYr** [comment]
Can't find images without ./assets/  .
3rd Party Indexes missing * at the beginning.
Also, I removed the black background from the banner, can it be added as well?

**Comment by DogancanYr** [comment]
⬆️⬆️⬆️?

**Comment by nbats** [comment]
3rd party has the *, idk what you mean by the first part, and I dont know if we want the black background removed, idk what it would look like

**Comment by DogancanYr** [comment]
You forgot to add the star when you edited it, but someone else took care of it.
https://github.com/fmhy/FMHYedit/commit/36232a932d2fcc2aa9c181ea26553d89af0b2255

It looks like this.
https://small.fileditchstuff.me/s8/vgvTipkpOUPxFdKyCGuf.png
resim
resim

**Comment by DogancanYr** [comment]
resim

**Comment by nbats** [comment]
fair enough I'll get it updated

**Comment by DogancanYr** [comment]
I also realised that half of these changes I made were not visible.
https://github.com/fmhy/FMHYedit/pull/2273/files
I didn't see anything about them being removed.

And really the discord github and bsky icons at the bottom are too small, can it really be made 30/25 pixels?

**Comment by nbats** [comment]
You made a lot of changes so I didnt have time to explain every single one I did / didnt do. And yeah I just changed the icons to 30.

**Comment by DogancanYr** [comment]
Will you change your mind if I tell you exactly what they do?
It feels like the things I've added or done are already self-explanatory.
If I'm increasing the size of something, it's added as small and it feels like it needs to be scaled up.

**Comment by nbats** [comment]
Possibly yes but a lot of the changes you made didnt make the cut for different reasons. And like I said I did increase the size.

**Pull request closed without merging**
