### PR TITLE
feat(Text Generation Tools): Add Repixify website

### PR DESCRIPTION
**Pull request by Tejasp2003**
Added a new Free Text Generation Tools Website

### Types of changes

- [ ]  Bad / Deleted sites removal
- [ ]  Grammar / Markdown fixes
- [x]  Content addition (sites, projects, tools, etc.)
- [ ]  New Wiki section

### Checklist:

- [x]  I have read the [contribution guide](https://rentry.co/Contrib-Guide).
- [x]  I have made sure to [search](https://raw.githubusercontent.com/fmhy/FMHYedit/main/single-page) before making any changes.
- [x]  My code follows the code style of this project.

### CODE REVIEW

**Comment by nbats** [comment]
thank you, we'll need to test it a bit but we'll add it once we do

**Comment by Tejasp2003** [comment]
Okay what's the estimated time to merge?

**Comment by nbats** [comment]
hard to say just depends on when someone has the time to try it

**Comment by Tejasp2003** [comment]
Is it checked now?

**Comment by god-damnit** [comment]
image

**Pull request closed without merging**
