### PR TITLE
add : userscript anna-archive external link

### PR DESCRIPTION
**Pull request by NormTurtle**
by ash

Anna's Archive - Show External Downloads

proof 
image

## Types of changes

- [ ] Bad / Deleted sites removal
- [ ] Grammar / Markdown fixes 
- [x] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [x] I have read the [contribution guide](https://rentry.co/Contrib-Guide).
- [x] I have made sure to [search](https://raw.githubusercontent.com/fmhy/FMHYedit/main/single-page) before making any changes. 
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by nbats** [comment]
thanks but I'll add next to anna's archive instead

**Comment by NormTurtle** [comment]
@nbats u could have just told me that! 
that it belong to another place.
so i could made another PR or something..

**Comment by nbats** [comment]
I'm sorry I haven't made the changes yet so you're welcome to send it yourself

Just add this to the description of Anna's:
` / [Expand Downloads](https://greasyfork.org/en/scripts/494262)`

**Comment by NormTurtle** [comment]
done #1898

**Pull request closed without merging**
