### PR TITLE
Update Non-English.md

### PR DESCRIPTION
**Pull request by Rust1667**
add spanish DDL site

### CODE REVIEW

**Comment by Rust1667** [comment]
Im sure
But the link shortener requires either the bypass userscript, or disabling ublock origin, or using adguard

**Comment by Rust1667** [comment]
that link shortener "mega-enlace" is also present in many of the spanish DDL sites already in the wiki

**Comment by nbats** [comment]
I have the userscript on and there was nothing seamless for me, it took me to like 5 pages and even to google. There's just no excuse for that.

**Comment by Rust1667** [comment]
Idk, Im with the userscript and its: a page (where you wait 30s), which leads to a pastebin. The pastebin has shorteners that are instabypassed to the file host.
I added one of those bypasses like yesterday to the userscript, might need to upadte it.

**Comment by nbats** [comment]
the issue is that most people wont have this script, so we're basically just sending a majority of people to a bad site

**Pull request closed without merging**
