### PR TITLE
Update Text-Tools.md

### PR DESCRIPTION
**Pull request by DogancanYr**
## Types of changes

- [ ] Bad / Deleted sites removal
- [ ] Grammar / Markdown fixes 
- [x] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [x] I have read the [contribution guide](https://rentry.co/Contrib-Guide).
- [x] I have made sure to [search](https://raw.githubusercontent.com/fmhy/FMHYedit/main/single-page) before making any changes. 
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by nbats** [comment]
Added the first, but looks like Eazy Po is for "Gettext" files only.

**Comment by DogancanYr** [comment]
> Added the first, but looks like Eazy Po is for "Gettext" files only.

Yes, but I wrote it this way because I couldn't find many such software that would be useful for someone who wants to translate.
It does not only support one file type, it supports text files like the one in the picture on the website.

**Comment by DogancanYr** [comment]
Also, matecat does not translate files automatically, it needs someone's help. It can be thought of as an online translation editor and only this one has a google api key that you can use for free. It might even get a star on the site because of this feature. It is even possible to translate the file by itself by pressing Alt+enter, but it is not automatic.

**Comment by nbats** [comment]
alright I'll get Eazy Po added and the other description updated

**Pull request merged**
