### PR TITLE
Update Pastebins

### PR DESCRIPTION
**Pull request by SnowzNZ**
## Types of changes

- [x] Bad / Deleted sites removal
- [x] Grammar / Markdown fixes 
- [ ] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [x] I have read the [contribution guide](https://rentry.co/Contrib-Guide).
- [x] I have made sure to [search](https://raw.githubusercontent.com/fmhy/FMHYedit/main/single-page) before making any changes. 
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by nbats** [comment]
are you working on this still? says its a draft

**Comment by SnowzNZ** [comment]
> are you working on this still? says its a draft

kinda, if you are onboard with this idea i can finalize everything

**Comment by nbats** [comment]
yeah I see no reason they cant be combined

**Comment by SnowzNZ** [comment]
should be good now. note that not everything is ordered as if higher is better.

i only removed a few that were just bad in my opinion and also added some extra tags and sources/mirrors to them.

if you have any problems with it lmk

**Comment by the9655a** [comment]
Hang on, why was this done again? I separated them so things were better organized and easier to find. We don't really want all the links in one big section, it can get messy.

**Comment by SnowzNZ** [comment]
> Hang on, why was this done again? I separated them so things were better organized and easier to find. We don't really want all the links in one big section, it can get messy.

They all pretty much do the same thing what's the point in having multiple sections. Just have a few select high quality ones

**Comment by nbats** [comment]
yeah they're all very similar and the section itself isn't very big or bloated anyways.

**Comment by the9655a** [comment]
Alr fair enough. But, I don't see the changes on the website or in .md file? I think something went wrong

**Comment by nbats** [comment]
my bad just got it fixed

**Pull request merged**
