### PR TITLE
Update gaming-tools.md - Add Just Dance Tools

### PR DESCRIPTION
**Pull request by Numerosityy**
Added Just Dance Tools section.

## Description
This section adds a ton of unique Just Dance content, across several platforms.

## Context
There is little to no Just Dance content on FMHY, and I wanted to add some reputable sources that I know of.

## Types of changes

- [ ] Bad / Deleted sites removal
- [ ] Grammar / Markdown fixes 
- [x] Content addition (sites, projects, tools, etc.)
- [x] New Wiki section

## Checklist:

- [x] I have read the [contribution guide](https://fmhy.net/other/contributing).
- [x] I have made sure to [search](https://api.fmhy.net/single-page) before making any changes. 
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by nbats** [comment]
The section looks good, but I don't think Just Dance is popular enough to warrant a section for anymore. I know it was very popular at points in the past, but sales have died down a lot afaik. Posting the gdrive links also seems too risky.

image

My suggestion would be to remove the gdrive stuff, take the rest, copy it to a [rentry page](https://rentry.co/), then we can post that as a whole.

**Comment by Numerosityy** [comment]
@nbats Done! lmk if you want anything changed
[Just Dance Megathread](https://rentry.co/just-dance-megathread)

**Comment by nbats** [comment]
perfect thank you, I'll get it added soon

**Comment by nbats** [comment]
also if you're looking for feedback or a place to share updates feel free to make a discord thread in #project-updates

**Pull request closed without merging**
