### PR TITLE
Update

### PR DESCRIPTION
**Pull request by DogancanYr**
## Types of changes

- [ ] Bad / Deleted sites removal
- [x] Grammar / Markdown fixes 
- [x] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

### CODE REVIEW

**Comment by the9655a** [comment]
Hey, you aren't supposed to edit the single page file. It'll cause problems since its auto updated based on all the other .md files.

**Comment by DogancanYr** [comment]
True...
I thought I'd send it with GitHub desktop, but somehow it did that.

**Comment by the9655a** [comment]
I think GitHub actions is interfering with this. I'd turn it off on your fork. That's what I did, and it doesn't affect the wiki when u make changes

**Comment by DogancanYr** [comment]
Bot is following me. :(  I have to do it a different way.

**Comment by DogancanYr** [comment]
Ok.

**Pull request closed without merging**
