### PR TITLE
Add: Anki entries

### PR DESCRIPTION
**Pull request by NameLessGO**
### 1* Change
Science / Math > Medical School > line: [CRAM.com](https://www.cram.com/medical) - Medical Flashcards

Change:
Added https://ankiweb.net/shared/decks?search=Med

Results:
* [AnkiWeb](https://ankiweb.net/shared/decks?search=Med), [CRAM.com](https://www.cram.com/medical) - Medical Flashcards

### 2* Change
Educational Tools > Study / Research > line: [Anki](https://apps.ankiweb.net/) / [Addons](https://github.com/tianshanghong/awesome-anki), [StudyLib](https://www.studylib.net/), [RemNote](https://www.remnote.com/) or [Flashcard Machine](https://www.flashcardmachine.com/) - Flashcard Tools

Change:
1. Changed Addons to Add-ons
3. Replace Add-ons link (previous with awesome anki link) with https://ankiweb.net/shared/addons
4. Add Awesome Anki: https://github.com/tianshanghong/awesome-anki
5. Add Decks: https://ankiweb.net/shared/decks

Results:
* ⭐ **[Anki](https://apps.ankiweb.net/)** / [Add-ons](https://ankiweb.net/shared/addons) / [Decks](https://ankiweb.net/shared/decks) / [Awesome Anki](https://github.com/tianshanghong/awesome-anki), [StudyLib](https://www.studylib.net/), [RemNote](https://www.remnote.com/) or [Flashcard Machine](https://www.flashcardmachine.com/) - Flashcard Tools

### 3* Change
Added [Anki xxxx Decks] for each subheading
Anki History Decks, Anki Chemistry Decks, Anki English Decks...

## Context

More detailed resources for Anki users

## Types of changes

- [ ] Bad / Deleted sites removal
- [X] Grammar / Markdown fixes 
- [X] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [x] I have read the [contribution guide](https://rentry.co/Contrib-Guide).
- [x] I have made sure to [search](https://raw.githubusercontent.com/fmhy/FMHYedit/main/single-page) before making any changes. 
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by NameLessGO** [comment]
Converted to Draft: couldn't check links properly due to daily search limit, will be testing every day to confirm

Should take 1-3 Days

**Comment by nbats** [comment]
thank you I got the anki section itself updated with your changes, but I'm not sure its worth adding every individual flash card page. We generally try to keep frontpages rather than a bunch of sub ones.

**Comment by NameLessGO** [comment]
##### Goal:
To make it easier and straightforward for students to find Flashcards of their interest

##### Before:
To access Anki Decks, the Language learning student (English) would go:

🍎 Educational Tools* > Educational Tools* > Study / Research > Anki / Decks > AnkiWeb (Assuming Users clicked on Deck**) > Search Deck: English

##### Now:
🍎 Education Tools > Language Learning > English: Anki English Decks


##### Observation:
*There is 🍎 Educational Tools page, and Educational tools as Heading

Is it intentional?

**Would assume that users are likely to only click in the first link of a line

Example: users are most likely to click on Anki because it is first on the left (Left-To-Right/Western users)

 Anki / Add-ons / Decks / Awesome Anki, StudyLib, RemNote or Flashcard Machine - Flashcard Tool

##### Extra: 
There are some decks which extrapolated a bit hence why moved to Draft to verify which decks would appear for:
* Space: Keyword: Astro, Space > Verify
* South Asia: Keyword: Asia > didn't know what was the URL to separate "South Asia"
* Periodic Table: Keyword: Periodic > same as above
* Other Language: Keyword: Sign (and another one) > verify

**Comment by nbats** [comment]
I get where you're coming from but we just never do this in terms of linking a bunch of the same website over and over on multiple lines. I think it would work better if they were all compiled somewhere like a rentry.

**Pull request closed without merging**
