### PR TITLE
Adding TheRetroSaga - Multi Platform gaming website

### PR DESCRIPTION
**Pull request by beingretrogamer**
## Description
This PR aims to add https://theretrosaga.com which is a mult- platform gaming website. This website hosts retro games from NES, SNES, Atari, Neo-Geo, Dos, etc.

## Context

This is an addition.

## Types of changes

- [ ] Bad / Deleted sites removal
- [ ] Grammar / Markdown fixes 
- [x] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [x] I have read the [contribution guide](https://rentry.co/Contrib-Guide).
- [x] I have made sure to [search](https://raw.githubusercontent.com/fmhy/FMHYedit/main/single-page) before making any changes. 
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by nbats** [comment]
Thank you but we got it added yesterday in the multi-console emulator section

**Comment by beingretrogamer** [comment]
Hi @nbats Sorry to bug you with this again but it got lost with this commit with other restructures - https://github.com/fmhy/FMHYedit/commit/97c32d736f8abd545a77dc3e98cb596207ed6989
Can you please re-add this?

**Comment by nbats** [comment]
its listed here: https://fmhy.net/storage#multi-console-browser-emulators

**Comment by beingretrogamer** [comment]
Thank @nbats for pointing! I searched for the link in the github search bar but it didn't show up anything for weird reason. Can you help me understand what this storage page is for? 

One last thing - I found a typo - The link text is "The Retro Sega" but it should but "The Retro Saga". I created a PR just now - https://github.com/fmhy/FMHYedit/pull/2065/files

**Comment by nbats** [comment]
Storage page is just where we keep lists that have gotten too big in main sections, but every storage section is linked somewhere in a main section. And I'll get your site bumped up a bit higher so people can find it easier.

**Comment by beingretrogamer** [comment]
Thanks for clarifying. Bumping up would be awesome! Thanks a ton :)

**Pull request closed without merging**
