### PR TITLE
Update Non-English.md

### PR DESCRIPTION
**Pull request by DogancanYr**
## Types of changes

- [ ] Bad / Deleted sites removal
- [ ] Grammar / Markdown fixes 
- [x] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [x] I have read the [contribution guide](https://rentry.co/Contrib-Guide).
- [x] I have made sure to [search](https://raw.githubusercontent.com/fmhy/FMHYedit/main/single-page) before making any changes. 
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by nbats** [comment]
thank you, I'll get it posted but in our nsfw section instead

**Comment by DogancanYr** [comment]
This site is no different from other added sites. What's the specialty?

**Comment by nbats** [comment]
Oh I didn't realize there were others that were nsfw, I'll get those moved too.

**Comment by DogancanYr** [comment]
It is written as Turkish Games, but there are translation patches for the games on the sites. (They open game files themselves and  translate them.) So it can remain as it is?

**Comment by nbats** [comment]
sure I'll update their tags

**Pull request closed without merging**
