### PR TITLE
Minor Typo & Formatting Fixes

### PR DESCRIPTION
**Pull request by devilspeech**
## Description

Fixed spacing, comma, and ampersand typos.
Changed w/ to with for consistency.
Updated Tiler description to be less confusing.

## Types of changes

- [ ] Bad / Deleted sites removal
- [X] Grammar / Markdown fixes 
- [ ] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [X] I have read the [contribution guide](https://fmhy.net/other/contributing).
- [X] I have made sure to [search](https://api.fmhy.net/single-page) before making any changes. 
- [X] My code follows the code style of this project.

### CODE REVIEW

**Comment by rhld16** [comment]
Are there any specific reasons to remove Oxford commas or elongate the contraction of with?

**Comment by ballszu** [comment]
I fucking hate that i cant tell if its a shitpost PR or a legit one.

**Comment by devilspeech** [comment]
Just for consistency with the rest of the wiki, only a small number of entries had the commas or contractions in that format. They're things I have seen fixed before so I just changed them along with the typos I noticed.

**Comment by nbats** [comment]
thank you I'll get it merged in a bit

**Pull request merged**
