### PR TITLE
Update MISCGuide.md

### PR DESCRIPTION
**Pull request by Reknilkcab**
## Description
Added www.detect-face-shape.com to MISCGuide.md - random section

## Context
Added new free beauty tool.

## Types of changes

- [ ] Bad / Deleted sites removal
- [ ] Grammar / Markdown fixes 
- [x] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [x] I have read the [contribution guide](https://rentry.co/Contrib-Guide).
- [x] I have made sure to [search](https://raw.githubusercontent.com/fmhy/FMHYedit/main/single-page) before making any changes. 
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by nbats** [comment]
thank you but I'm not sure if this is very useful to most people

**Comment by Reknilkcab** [comment]
> thank you but I'm not sure if this is very useful to most people

@nbats Thanks for taking a look. I know that this might seem not very useful at first sight, but there is actually high search volume (>100k search queries per month) for this type of tool. So I would consider it as useful afterall.

**Comment by nbats** [comment]
alright fair enough I'll get it added

**Comment by qweered** [comment]
https://www.faceshape.com/ has better features and faster

**Comment by Reknilkcab** [comment]
@qweered You're right that it's indeed faster, which is a great advantage. 
I've noticed, though, that for specifically determining face shapes, the approach used by https://detect-face-shape.com/ might offer a bit more depth. It provides users with probabilities of different face shapes, capturing the nuance that most faces don't fit perfectly into a single category.

**Comment by nbats** [comment]
> https://www.faceshape.com/ has better features and faster

alright we'll add both together

**Pull request closed without merging**
