### PR TITLE
Link updates

### PR DESCRIPTION
**Pull request by Atropa-Solanaceae**
Cloudflare warp scripts no longer function & stacer has now been abandoned.

### CODE REVIEW

**Comment by nbats** [comment]
applied both changes ty

**Comment by nbats** [comment]
What part of warp scripts are broken, they seem to be working for others in our discord.

**Comment by Atropa-Solanaceae** [comment]
That's odd, I couldn't get them to function on any network connection.

**Comment by Atropa-Solanaceae** [comment]
How can I join the discord in order to test the scripts?

**Comment by BNX070** [comment]
> That's odd, I couldn't get them to function on any network connection.

It's still working, you prolly aren't using them right or cloudfare warp is blocked by your isp (it can happen)

**Comment by zinklog2** [comment]
> How can I join the discord in order to test the scripts?

https://fmhy.divolt.xyz/ you can join here, which is bridged to our private discord server

**Comment by BNX070** [comment]
> How can I join the discord in order to test the scripts?

There aren't any scripts on discord, you'll be testing these same scripts lol.
But if you wanna join search FMHY Divolt

**Comment by Atropa-Solanaceae** [comment]
Thanks for your help

**Pull request closed without merging**
