### PR TITLE
Star RetroAchievements, Remove CH from OS games

### PR DESCRIPTION
**Pull request by nullish-cat**
## Description
* Starred RetroAchievements
* Removed CloneHero from the Open Source list

## Context
Starring RA since it adds quite a lot to classic games - not only achievements, but leaderboards, speedrun times, etc. That and it supports tons of games.

Clone Hero, while pretty good, is not open source and is likely to stay closed. Could probably be re-added in a separate rhythm/music game section.

## Types of changes

- [ ] Bad / Deleted sites removal
- [ ] Grammar / Markdown fixes 
- [ ] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [x] I have read the [contribution guide](https://rentry.co/Contrib-Guide).
- [x] I have made sure to [search](https://raw.githubusercontent.com/fmhy/FMHYedit/main/single-page) before making any changes. 
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by nbats** [comment]
Thank you, wont let me merge but I got both changed added

**Comment by nullish-cat** [comment]
> Thank you, wont let me merge but I got both changed added

Still looks unchanged, did you commit?

**Comment by nbats** [comment]
sorry I'll merge all the changes once I'm done editing

**Comment by nullish-cat** [comment]
Alright nw

**Pull request closed without merging**
