### PR TITLE
Update GamingPiracyGuide.md

### PR DESCRIPTION
**Pull request by DogancanYr**
## Types of changes

- [ ] Bad / Deleted sites removal
- [ ] Grammar / Markdown fixes 
- [x] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [x] I have read the [contribution guide](https://rentry.co/Contrib-Guide).
- [x] I have made sure to [search](https://raw.githubusercontent.com/fmhy/FMHYedit/main/single-page) before making any changes. 
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by DogancanYr** [comment]
😊😊😊😊

**Comment by nbats** [comment]
Thank you but adding this might be a bad call. I know its annoying but at the end of the day we're on the same side as dodi and don't want to piss them off.

**Comment by DogancanYr** [comment]
> Thank you but adding this might be a bad call. I know its annoying but at the end of the day we're on the same side as dodi and don't want to piss them off.

It does not completely bypass.It just allows you to pass as a normal user.

**Comment by nbats** [comment]
alright fair enough

**Pull request closed without merging**
