### PR TITLE
Update GamingPiracyGuide.md

### PR DESCRIPTION
**Pull request by DogancanYr**
https://game-repack.site = Site contains more than one repack publisher.
https://gamedrive.org = It has been removed but it can be like this.

## Types of changes

- [ ] Bad / Deleted sites removal
- [ ] Grammar / Markdown fixes 
- [x] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [x] I have read the [contribution guide](https://rentry.co/Contrib-Guide).
- [x] I have made sure to [search](https://raw.githubusercontent.com/fmhy/FMHYedit/main/single-page) before making any changes. 
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by nbats** [comment]
I'm sorry but GameDrive has a really bad rep in the community for their history of stealing stuff from GameSDrive and adding paywalls. We're also very close to the GameSDrive team, so adding a site that is stealing their name is a bad call.

As far as the other site goes, it doesn't have the best reputation either, but we'll look into it a bit more.

**Comment by DogancanYr** [comment]
I wouldn't have tried to add it if I knew it was like this, I knew it was adding fake download links last time.
I wondered where the conversations took place. I still haven't found that it says something like this .

**Comment by nbats** [comment]
It happened a long time ago, and they dont have paywalls anymore, but it just ruined their reputation, and people already didn't like them just for stealing GameSDrive's name.

**Comment by Gamepagge** [comment]
> It happened a long time ago, and they dont have paywalls anymore, but it just ruined their reputation, and people already didn't like them just for stealing GameSDrive's name.

paywalls in your ass ?

**Pull request closed without merging**
