### PR TITLE
Update AI.md

### PR DESCRIPTION
**Pull request by joethesaint**
## Types of changes

- [ ] Bad / Deleted sites removal
- [ ] Grammar / Markdown fixes 
- [ ] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [ ] I have read the [contribution guide](https://rentry.co/Contrib-Guide).
- [ ] I have made sure to [search](https://raw.githubusercontent.com/fmhy/FMHYedit/main/single-page) before making any changes. 
- [ ] My code follows the code style of this project.

### CODE REVIEW

**Comment by nbats** [comment]
thanks for sharing but we'll need to try it out first

**Comment by joethesaint** [comment]
Can it still be merged after trying it out?

**Comment by joethesaint** [comment]
Since it's been closed

**Comment by nbats** [comment]
it was giving me a error earlier for whatever reason sorry, but we will get it added eventually

**Comment by joethesaint** [comment]
Okay, I will check back. It is my first contribution here and I would love to contribute more as time goes by.

**Comment by joethesaint** [comment]
I prefer discord, but will I still get the contributor tag? And is there a walkthrough for the discord?

**Pull request closed without merging**
