### PR TITLE
Update AdblockVPNGuide.md

### PR DESCRIPTION
**Pull request by DogancanYr**

### CODE REVIEW

**Comment by nbats** [comment]
ty but we'll need to check it out first

**Comment by DogancanYr** [comment]
> ty but we'll need to check it out first

It is already a well known antivirus. I don't think there will be a problem.

**Comment by DogancanYr** [comment]
What kind of check will it be?

**Comment by nbats** [comment]
sorry but according to one of our mods bitdefender is anti-piracy and also gets many false positives.

**Comment by DogancanYr** [comment]
> sorry but according to one of our mods bitdefender is anti-piracy and also gets many false positives.

I'm trying to add vpn here, not anti virus.

**Comment by nbats** [comment]
I see but if they're anti-piracy I still dont think its a good idea to direct people to them

**Comment by DogancanYr** [comment]
> I see but if they're anti-piracy I still dont think its a good idea to direct people to them

How other vpns work, this vpn works the same, there is no difference, and even torrenting works. (also free)

**Comment by nbats** [comment]
okay fair enough we'll take a closer look

**Pull request closed without merging**
