### PR TITLE
Update GamingPiracyGuide.md

### PR DESCRIPTION
**Pull request by DogancanYr**

### CODE REVIEW

**Comment by DogancanYr** [comment]
In the original version, there is no auto-generate file and the achievements are incorrect.

**Comment by DogancanYr** [comment]
> In the original version, there is no auto-generate file and the achievements are incorrect.

Why ?

**Comment by nbats** [comment]
sorry but it only has 18 stars so we'll need to at least read through it ourselves before adding

**Comment by DogancanYr** [comment]
> sorry but it only has 18 stars so we'll need to at least read through it ourselves before adding
Original version was problematic, so a new update was made on cs.rin.ru by users (2 months ago) and this is its continuation and slightly improved version.

**Comment by nbats** [comment]
Alright fair enough, I'll get it added

**Pull request merged**
